### PR TITLE
Openvpn tunnel

### PR DESCRIPTION
**Pull request by brewn**
Applied revisions.

### CODE REVIEW

**Comment by yoneal** [comment]
Hi @brewn thanks on cleaning up the article, I am wondering why you removed the section about firewall config, did you not need it in your setup?

**Comment by brewn** [comment]
@yoneal It looks like OpenVPN-AS creates the necessary firewall rules based on the configuration options you set within the admin access panel.

**Comment by alexfornuto** [comment]
@yoneal are there any other issues preventing you from merging this?

**Comment by yoneal** [comment]
@brewn I see, that is good to know!
@alexfornuto none at all, was just swamped with other stuff..

**Pull request merged**
